import type { Listing } from "./types";
import { imagesFor } from "./images";

const img = (seed: string, n = 4): string[] =>
  Array.from({ length: n }, () => seed);

const RAW_LISTINGS: Listing[] = [
  {
    id: "ash-001",
    title: "2-комн квартира в новостройке, Беркарарлык",
    dealType: "sale",
    propertyType: "apartment",
    price: 480000,
    currency: "TMT",
    rooms: 2,
    area: 68,
    floor: 4,
    totalFloors: 9,
    cityId: "ashgabat",
    district: "Беркарарлык",
    address: "ул. Битарап Туркменистан, 58",
    description:
      "Современная двухкомнатная квартира в сданной новостройке. Итальянская кухня, кондиционеры, закрытый двор с парковкой. До центра 10 минут на машине.",
    images: img("ash001"),
    author: { name: "Мерген", role: "owner", phone: "+99365 123 45 67" },
    amenities: ["Кондиционер", "Закрытый двор", "Парковка", "Лифт", "Балкон"],
    publishedAt: "2026-04-18T09:10:00Z",
    lat: 37.9601,
    lng: 58.3261,
  },
  {
    id: "ash-002",
    title: "Элитная 3-комн, Арчабил, вид на Копетдаг",
    dealType: "sale",
    propertyType: "apartment",
    price: 1250000,
    currency: "TMT",
    rooms: 3,
    area: 124,
    floor: 8,
    totalFloors: 12,
    cityId: "ashgabat",
    district: "Арчабил",
    address: "пр. Арчабил, 64",
    description:
      "Просторная квартира в элитном комплексе с консьержем и подземным паркингом. Мраморные полы, панорамные окна на горы Копетдаг.",
    images: img("ash002"),
    author: { name: "Агентство «Ак Өй»", role: "agency", phone: "+99312 45 10 10" },
    amenities: [
      "Консьерж",
      "Подземный паркинг",
      "Панорамные окна",
      "Тёплый пол",
      "Кондиционер",
    ],
    publishedAt: "2026-04-19T14:25:00Z",
    lat: 37.9195,
    lng: 58.3789,
  },
  {
    id: "ash-003",
    title: "1-комн на Парахат 7, недорого",
    dealType: "sale",
    propertyType: "apartment",
    price: 265000,
    currency: "TMT",
    rooms: 1,
    area: 42,
    floor: 2,
    totalFloors: 5,
    cityId: "ashgabat",
    district: "Парахат 7",
    address: "Парахат 7, дом 22",
    description:
      "Уютная однокомнатная квартира. Сделан свежий ремонт, установлены пластиковые окна и сплит-система. Рядом школа, детский сад, супермаркет.",
    images: img("ash003"),
    author: { name: "Айна", role: "owner", phone: "+99363 55 44 33" },
    amenities: ["Сплит-система", "Пластиковые окна", "Балкон"],
    publishedAt: "2026-04-20T07:40:00Z",
    lat: 37.948,
    lng: 58.402,
  },
  {
    id: "ash-004",
    title: "Частный дом 4-комн, Бикрова, 6 соток",
    dealType: "sale",
    propertyType: "house",
    price: 980000,
    currency: "TMT",
    rooms: 4,
    area: 210,
    cityId: "ashgabat",
    district: "Бикрова",
    address: "ул. Гёроглы, 12",
    description:
      "Двухэтажный дом в тихом районе. Большой двор с виноградником и местом для машины. Газ, вода, канализация — всё центральное.",
    images: img("ash004"),
    author: { name: "Бегенч", role: "owner", phone: "+99365 77 88 99" },
    amenities: ["Двор", "Гараж", "Сад", "Центральный газ"],
    publishedAt: "2026-04-15T12:00:00Z",
    lat: 37.988,
    lng: 58.362,
  },
  {
    id: "ash-005",
    title: "Аренда 2-комн, Копетдаг, посуточно",
    dealType: "rent",
    propertyType: "apartment",
    price: 450,
    currency: "TMT",
    rooms: 2,
    area: 60,
    floor: 5,
    totalFloors: 9,
    cityId: "ashgabat",
    district: "Копетдаг",
    address: "ул. 2028 (Горького), 45",
    description:
      "Сдаётся посуточно чистая двухкомнатная квартира. Wi-Fi, стиральная машина, постельное бельё и полотенца включены. Оплата за сутки.",
    images: img("ash005"),
    author: { name: "Джемал", role: "owner", phone: "+99364 11 22 33" },
    amenities: ["Wi-Fi", "Стиральная машина", "Кондиционер", "Посуточно"],
    publishedAt: "2026-04-21T06:00:00Z",
    lat: 37.935,
    lng: 58.35,
  },
  {
    id: "ash-006",
    title: "Аренда 3-комн долгосрочно, Багтыярлык",
    dealType: "rent",
    propertyType: "apartment",
    price: 5500,
    currency: "TMT",
    rooms: 3,
    area: 92,
    floor: 6,
    totalFloors: 14,
    cityId: "ashgabat",
    district: "Багтыярлык",
    address: "ул. А. Ниязова, 174",
    description:
      "Сдаётся на длительный срок. С мебелью и техникой, два кондиционера, две лоджии. Оплата помесячно, залог 1 месяц.",
    images: img("ash006"),
    author: { name: "Оразгуль", role: "owner", phone: "+99365 33 22 11" },
    amenities: ["Мебель", "Техника", "Два кондиционера", "Лоджия"],
    publishedAt: "2026-04-17T15:30:00Z",
    lat: 37.96,
    lng: 58.39,
  },
  {
    id: "ash-007",
    title: "Офис 120 м² в центре, БЦ «Беркарар»",
    dealType: "rent",
    propertyType: "commercial",
    price: 12000,
    currency: "TMT",
    area: 120,
    floor: 3,
    totalFloors: 7,
    cityId: "ashgabat",
    district: "Центр",
    address: "пр. Битарап Туркменистан, 111",
    description:
      "Офисное помещение open-space + 2 переговорных. Стабильный интернет, охрана 24/7, подземный паркинг на 4 места включён.",
    images: img("ash007"),
    author: { name: "БЦ Беркарар", role: "agency", phone: "+99312 22 33 44" },
    amenities: ["Охрана", "Интернет", "Паркинг", "Кондиционирование"],
    publishedAt: "2026-04-12T10:00:00Z",
    lat: 37.9565,
    lng: 58.389,
  },
  {
    id: "ash-008",
    title: "Участок 8 соток под ИЖС, Гаудан",
    dealType: "sale",
    propertyType: "land",
    price: 320000,
    currency: "TMT",
    area: 800,
    cityId: "ashgabat",
    district: "Гаудан",
    address: "мкр Гаудан-юг, ул. 3",
    description:
      "Ровный участок, документы в порядке, все коммуникации по границе. Отличное место для строительства семейного дома.",
    images: img("ash008"),
    author: { name: "Довлет", role: "owner", phone: "+99363 90 80 70" },
    amenities: ["Электричество", "Вода", "Ровный участок"],
    publishedAt: "2026-04-10T11:20:00Z",
    lat: 37.89,
    lng: 58.4,
  },
  {
    id: "ash-009",
    title: "Комната в 3-комн квартире, Мир 1",
    dealType: "rent",
    propertyType: "room",
    price: 1200,
    currency: "TMT",
    area: 14,
    floor: 3,
    totalFloors: 5,
    cityId: "ashgabat",
    district: "Мир 1",
    address: "Мир 1, дом 14",
    description:
      "Сдаётся комната девушке. Соседка — студентка. Интернет, стиральная машина, кухня и санузел в общем пользовании.",
    images: img("ash009", 3),
    author: { name: "Майса", role: "owner", phone: "+99365 44 55 66" },
    amenities: ["Wi-Fi", "Стиральная машина", "Общая кухня"],
    publishedAt: "2026-04-20T18:00:00Z",
    lat: 37.955,
    lng: 58.38,
  },
  {
    id: "ash-010",
    title: "Новостройка 4-комн, 30 мкр, свободная планировка",
    dealType: "sale",
    propertyType: "apartment",
    price: 1650000,
    currency: "TMT",
    rooms: 4,
    area: 156,
    floor: 10,
    totalFloors: 14,
    cityId: "ashgabat",
    district: "30 мкр",
    address: "30 мкр, дом 7",
    description:
      "Квартира в сданном доме премиум-класса. Свободная планировка, итальянская сантехника, два санузла, кладовая.",
    images: img("ash010"),
    author: { name: "Агентство «Ак Өй»", role: "agency", phone: "+99312 45 10 10" },
    amenities: ["Два санузла", "Кладовая", "Кондиционер", "Лифт"],
    publishedAt: "2026-04-14T09:00:00Z",
    lat: 37.95,
    lng: 58.41,
  },
  {
    id: "tka-001",
    title: "3-комн квартира в центре Туркменабата",
    dealType: "sale",
    propertyType: "apartment",
    price: 380000,
    currency: "TMT",
    rooms: 3,
    area: 78,
    floor: 3,
    totalFloors: 5,
    cityId: "turkmenabat",
    district: "Центр",
    address: "ул. Сейди, 26",
    description:
      "Квартира в кирпичном доме, тёплая, окна на юг. Рядом базар, школа, поликлиника. В шаговой доступности остановка.",
    images: img("tka001"),
    author: { name: "Реджеп", role: "owner", phone: "+99365 21 34 56" },
    amenities: ["Пластиковые окна", "Балкон", "Кладовка"],
    publishedAt: "2026-04-16T10:10:00Z",
    lat: 39.0725,
    lng: 63.5784,
  },
  {
    id: "tka-002",
    title: "Дом 5-комн с садом, Саят",
    dealType: "sale",
    propertyType: "house",
    price: 550000,
    currency: "TMT",
    rooms: 5,
    area: 240,
    cityId: "turkmenabat",
    district: "Саят",
    address: "Саят, ул. Гёрогл,  7",
    description:
      "Просторный дом для большой семьи. 10 соток, сад с абрикосами и гранатом. Летняя кухня, тандыр, отдельная гостевая.",
    images: img("tka002"),
    author: { name: "Атамурат", role: "owner", phone: "+99363 14 15 16" },
    amenities: ["Сад", "Тандыр", "Летняя кухня", "Гараж"],
    publishedAt: "2026-04-11T08:30:00Z",
    lat: 38.85,
    lng: 63.85,
  },
  {
    id: "tka-003",
    title: "Аренда 1-комн, Туркменабат центр",
    dealType: "rent",
    propertyType: "apartment",
    price: 1500,
    currency: "TMT",
    rooms: 1,
    area: 38,
    floor: 2,
    totalFloors: 4,
    cityId: "turkmenabat",
    district: "Центр",
    address: "ул. Независимости, 14",
    description:
      "Небольшая квартира после ремонта. Сдаётся надолго, с мебелью. Оплата помесячно.",
    images: img("tka003", 3),
    author: { name: "Гулалек", role: "owner", phone: "+99364 98 76 54" },
    amenities: ["Мебель", "Кондиционер", "Новый ремонт"],
    publishedAt: "2026-04-19T11:00:00Z",
    lat: 39.075,
    lng: 63.58,
  },
  {
    id: "tka-004",
    title: "Магазин 60 м² на оживлённой улице",
    dealType: "rent",
    propertyType: "commercial",
    price: 4000,
    currency: "TMT",
    area: 60,
    cityId: "turkmenabat",
    district: "Центр",
    address: "ул. Магтымгулы, 33",
    description:
      "Готовое помещение под магазин или кафе. Высокий пешеходный трафик, витринные окна, два входа.",
    images: img("tka004"),
    author: { name: "Нуры", role: "agent", phone: "+99365 66 77 88" },
    amenities: ["Витрина", "Два входа", "Кондиционер"],
    publishedAt: "2026-04-13T12:45:00Z",
  },
  {
    id: "mary-001",
    title: "2-комн квартира, центр Мары",
    dealType: "sale",
    propertyType: "apartment",
    price: 320000,
    currency: "TMT",
    rooms: 2,
    area: 56,
    floor: 4,
    totalFloors: 5,
    cityId: "mary",
    district: "Центр",
    address: "ул. Молланепес, 19",
    description:
      "Квартира на среднем этаже, две лоджии, не угловая. Сделан косметический ремонт, чисто.",
    images: img("mary001"),
    author: { name: "Байрам", role: "owner", phone: "+99363 41 41 41" },
    amenities: ["Две лоджии", "Пластиковые окна"],
    publishedAt: "2026-04-17T13:15:00Z",
    lat: 37.596,
    lng: 61.833,
  },
  {
    id: "mary-002",
    title: "Дом 3-комн в Байрамали",
    dealType: "sale",
    propertyType: "house",
    price: 260000,
    currency: "TMT",
    rooms: 3,
    area: 120,
    cityId: "mary",
    district: "Байрамали",
    address: "Байрамали, ул. Туркменбаши, 11",
    description:
      "Одноэтажный дом, 4 сотки, плодовые деревья, колодец, гараж на 2 машины.",
    images: img("mary002"),
    author: { name: "Сердар", role: "owner", phone: "+99365 10 20 30" },
    amenities: ["Гараж", "Колодец", "Сад"],
    publishedAt: "2026-04-09T09:00:00Z",
    lat: 37.62,
    lng: 62.16,
  },
  {
    id: "mary-003",
    title: "Аренда 2-комн посуточно, Мары центр",
    dealType: "rent",
    propertyType: "apartment",
    price: 280,
    currency: "TMT",
    rooms: 2,
    area: 50,
    floor: 3,
    totalFloors: 5,
    cityId: "mary",
    district: "Центр",
    address: "ул. Махтумкули, 8",
    description:
      "Чистая квартира для командированных. Документы для отчётности предоставляем. Минимальный срок — 1 сутки.",
    images: img("mary003", 3),
    author: { name: "Мая", role: "agent", phone: "+99364 22 33 44" },
    amenities: ["Wi-Fi", "Посуточно", "Кондиционер"],
    publishedAt: "2026-04-20T20:00:00Z",
  },
  {
    id: "das-001",
    title: "3-комн в Дашогузе, Гурбансолтан",
    dealType: "sale",
    propertyType: "apartment",
    price: 290000,
    currency: "TMT",
    rooms: 3,
    area: 70,
    floor: 2,
    totalFloors: 5,
    cityId: "dashoguz",
    district: "Гурбансолтан",
    address: "Гурбансолтан этрапы, ул. 15",
    description:
      "Квартира в кирпичном доме, раздельные комнаты, не угловая. Торг уместен при быстрой сделке.",
    images: img("das001"),
    author: { name: "Ораз", role: "owner", phone: "+99365 50 60 70" },
    amenities: ["Раздельные комнаты", "Балкон"],
    publishedAt: "2026-04-16T14:00:00Z",
    lat: 41.836,
    lng: 59.964,
  },
  {
    id: "das-002",
    title: "Частный дом 4-комн, Кёнеургенч",
    dealType: "sale",
    propertyType: "house",
    price: 220000,
    currency: "TMT",
    rooms: 4,
    area: 160,
    cityId: "dashoguz",
    district: "Кёнеургенч",
    address: "Кёнеургенч, ул. Гёроглы, 24",
    description:
      "Дом с большим двором, отдельная кухня и летняя веранда. 6 соток, плодовый сад.",
    images: img("das002"),
    author: { name: "Аман", role: "owner", phone: "+99363 30 30 30" },
    amenities: ["Сад", "Веранда", "Тандыр"],
    publishedAt: "2026-04-08T08:00:00Z",
  },
  {
    id: "das-003",
    title: "Аренда 1-комн, Дашогуз центр",
    dealType: "rent",
    propertyType: "apartment",
    price: 1100,
    currency: "TMT",
    rooms: 1,
    area: 36,
    floor: 4,
    totalFloors: 5,
    cityId: "dashoguz",
    district: "Центр",
    address: "ул. С.А. Ниязова, 7",
    description:
      "Сдаётся на длительный срок. С мебелью, есть интернет и кондиционер.",
    images: img("das003", 3),
    author: { name: "Лейли", role: "owner", phone: "+99365 12 13 14" },
    amenities: ["Мебель", "Wi-Fi", "Кондиционер"],
    publishedAt: "2026-04-19T09:15:00Z",
  },
  {
    id: "bal-001",
    title: "2-комн квартира, Балканабат центр",
    dealType: "sale",
    propertyType: "apartment",
    price: 275000,
    currency: "TMT",
    rooms: 2,
    area: 58,
    floor: 3,
    totalFloors: 5,
    cityId: "balkanabat",
    district: "Центр",
    address: "ул. Магтымгулы, 57",
    description:
      "Квартира с хорошим ремонтом в центре города. Рядом школа, магазины, парк.",
    images: img("bal001"),
    author: { name: "Гельды", role: "owner", phone: "+99363 77 77 77" },
    amenities: ["Ремонт", "Балкон", "Кладовка"],
    publishedAt: "2026-04-15T10:30:00Z",
    lat: 39.51,
    lng: 54.367,
  },
  {
    id: "bal-002",
    title: "Дом у моря, Джебел",
    dealType: "sale",
    propertyType: "house",
    price: 410000,
    currency: "TMT",
    rooms: 4,
    area: 180,
    cityId: "balkanabat",
    district: "Джебел",
    address: "Джебел, ул. Приморская, 4",
    description:
      "Дом в 15 минутах от побережья. Прохладный двор, беседка, сад, скважина с питьевой водой.",
    images: img("bal002"),
    author: { name: "Курбан", role: "owner", phone: "+99365 88 99 00" },
    amenities: ["Скважина", "Беседка", "Сад"],
    publishedAt: "2026-04-07T11:00:00Z",
  },
  {
    id: "tkb-001",
    title: "Апартаменты на Авазе, вид на Каспий",
    dealType: "rent",
    propertyType: "apartment",
    price: 800,
    currency: "TMT",
    rooms: 2,
    area: 64,
    floor: 7,
    totalFloors: 12,
    cityId: "turkmenbashi",
    district: "Аваза",
    address: "НТЗ «Аваза», блок C-7",
    description:
      "Сдаётся посуточно в курортной зоне Аваза. Вид на море, бассейн и пляж — в пешей доступности. Идеально для отпуска.",
    images: img("tkb001"),
    author: { name: "Rest Aваза", role: "agency", phone: "+99312 50 50 50" },
    amenities: ["Вид на море", "Бассейн", "Кондиционер", "Посуточно"],
    publishedAt: "2026-04-21T05:00:00Z",
    lat: 40.0216,
    lng: 52.9698,
  },
  {
    id: "tkb-002",
    title: "Квартира 3-комн в Туркменбаши",
    dealType: "sale",
    propertyType: "apartment",
    price: 420000,
    currency: "TMT",
    rooms: 3,
    area: 82,
    floor: 5,
    totalFloors: 9,
    cityId: "turkmenbashi",
    district: "Центр",
    address: "ул. Туркменбаши, 42",
    description:
      "Просторная квартира с видом на залив. Хороший ремонт, мебель остаётся.",
    images: img("tkb002"),
    author: { name: "Максат", role: "owner", phone: "+99364 71 82 93" },
    amenities: ["Мебель", "Вид на залив", "Кондиционер"],
    publishedAt: "2026-04-13T15:45:00Z",
  },
  {
    id: "tej-001",
    title: "Дом 3-комн, Теджен",
    dealType: "sale",
    propertyType: "house",
    price: 180000,
    currency: "TMT",
    rooms: 3,
    area: 110,
    cityId: "tejen",
    district: "Центр",
    address: "Теджен, ул. Махтумкули, 3",
    description:
      "Аккуратный дом с 4 сотками, плодовый сад, гараж. Тихий район.",
    images: img("tej001"),
    author: { name: "Халмурад", role: "owner", phone: "+99365 01 02 03" },
    amenities: ["Сад", "Гараж"],
    publishedAt: "2026-04-05T10:00:00Z",
  },
  {
    id: "bay-001",
    title: "1-комн квартира в Байрамали",
    dealType: "rent",
    propertyType: "apartment",
    price: 900,
    currency: "TMT",
    rooms: 1,
    area: 34,
    floor: 2,
    totalFloors: 4,
    cityId: "bayramaly",
    district: "Центр",
    address: "Байрамали, ул. Туркменбаши, 9",
    description:
      "Уютная студия, сдаётся долгосрочно. Вся необходимая мебель и техника.",
    images: img("bay001", 3),
    author: { name: "Тачмурад", role: "owner", phone: "+99365 25 25 25" },
    amenities: ["Мебель", "Техника", "Кондиционер"],
    publishedAt: "2026-04-18T16:00:00Z",
  },
  {
    id: "ash-011",
    title: "Аренда дома 5-комн, Хитровка",
    dealType: "rent",
    propertyType: "house",
    price: 15000,
    currency: "TMT",
    rooms: 5,
    area: 260,
    cityId: "ashgabat",
    district: "Хитровка",
    address: "ул. Хитровка, 98",
    description:
      "Большой дом для семьи или под представительство. 8 соток, бассейн, беседка, 3 санузла, автоматические ворота.",
    images: img("ash011"),
    author: { name: "Агентство «Ак Өй»", role: "agency", phone: "+99312 45 10 10" },
    amenities: ["Бассейн", "Автоматические ворота", "3 санузла", "Сад"],
    publishedAt: "2026-04-12T14:20:00Z",
    lat: 37.97,
    lng: 58.34,
  },
  {
    id: "ash-012",
    title: "Торговая площадь 200 м², пр. Битарап",
    dealType: "rent",
    propertyType: "commercial",
    price: 22000,
    currency: "TMT",
    area: 200,
    floor: 1,
    cityId: "ashgabat",
    district: "Центр",
    address: "пр. Битарап Туркменистан, 78",
    description:
      "Первая линия, отдельный вход, высокие потолки, стеклянная витрина. Под магазин, ресторан или салон.",
    images: img("ash012"),
    author: { name: "БЦ Беркарар", role: "agency", phone: "+99312 22 33 44" },
    amenities: ["Первая линия", "Витрина", "Парковка"],
    publishedAt: "2026-04-14T17:00:00Z",
  },
];

export const LISTINGS: Listing[] = RAW_LISTINGS.map((l) => ({
  ...l,
  images: imagesFor(l.propertyType, l.id, Math.max(3, l.images.length || 4)),
}));

export function findListing(id: string): Listing | undefined {
  return LISTINGS.find((l) => l.id === id);
}
